export const licensesContent = {
  school: {
    title: 'School',
    description: 'Empower young minds to turn empathy into action',
    icon: '/assets/images/license/image-add/Vector-1.svg',
    tiers: [
      {
        id: 'school-small',
        name: 'ChangeMaker School - Small',
        price: '$599',
        period: '1 year validity',
        benefits: ['500 students', '1 year validity', '$599 on renewal'],
      },
      {
        id: 'school-medium',
        name: 'ChangeMaker School - Medium',
        price: '$799',
        period: '1 year validity',
        benefits: ['800 students', '1 year validity', '$799 on renewal'],
      },
      {
        id: 'school-big',
        name: 'ChangeMaker School - Big',
        price: '$1,199',
        period: '1 year validity',
        benefits: ['1,100 students', '1 year validity', '$1,199 on renewal'],
      },
    ],
    visitPath: '/reallives/school',
    registerPath: '/reallives/register/school',
    registerUrl: 'https://reallivesworld.com/register-school',
  },

  university: {
    title: 'University',
    description: 'Bridge the gap between learning and real-world impact',
    icon: '/assets/images/license/image-add/Vector-2.svg',
    tiers: [
      {
        id: 'university-uni-50',
        name: 'Uni 50',
        price: '$299',
        period: '1 year validity',
        benefits: ['1 year validity', '50 Student', 'Buy License'],
      },
      {
        id: 'university-uni-100',
        name: 'Uni 100',
        price: '$499',
        period: '1 year validity',
        benefits: ['1 year validity', '100 students', 'Buy License'],
      },
      {
        id: 'university-uni-150',
        name: 'Uni 150',
        price: '$749',
        period: '1 year validity',
        benefits: ['1 year validity', '150 students', 'Buy License'],
      },
      {
        id: 'university-uni-200',
        name: 'Uni 200',
        price: '$999',
        period: '1 year validity',
        benefits: ['1 year validity', '200 students', 'Buy License'],
      },
      {
        id: 'university-uni-50-hidden',
        name: 'Uni 50',
        price: '$1,249',
        period: '1 Year Validity',
        benefits: ['1 Year Validity', '250 students', 'Buy License'],
      },
      {
        id: 'university-uni-100-hidden',
        name: 'Uni 100',
        price: '$1,449',
        period: '1 year validity',
        benefits: ['1 year validity', '300 students', 'Buy License'],
      },
    ],
    visitPath: '/reallives/university',
    registerPath: '/reallives/register/university',
    registerUrl: 'https://reallivesworld.com/register-university',
  },

  homeschooler: {
    title: 'Home Schooler',
    description: 'Help your child grow wiser about the world — one life at a time',
    icon: '/assets/images/license/image-add/Vector-3.svg',
    tiers: [
      {
        id: 'homeschooler-family-1',
        name: 'Family 1',
        price: '$50',
        period: '1 year validity',
        benefits: ['2 Parents + 1 Child (13+)', '1 year validity', 'Max Lives: 50'],
      },
      {
        id: 'homeschooler-family-2',
        name: 'Family 2',
        price: '$75',
        period: '1 year validity',
        benefits: ['2 Parents + 2 Children (13+)', '1 year validity', 'Max Lives: 75'],
      },
      {
        id: 'homeschooler-family-3',
        name: 'Family 3',
        price: '$100',
        period: '1 year validity',
        benefits: ['2 Parents + 3 Children (13+)', '1 year validity', 'Max Lives: 100'],
      },
    ],
    visitPath: '/reallives/homeschooler',
    registerPath: '/reallives/register/homeschooler',
    registerUrl: 'https://reallivesworld.com/register-family',
  },

  gamer: {
    title: 'Gamer',
    description: 'Live a billion lives. Discover who you could be',
    icon: '/assets/images/license/image-add/vector-4.svg',
    tiers: [
      {
        id: 'gamer-wanderer',
        name: 'Wanderer',
        price: '$7.99',
        period: '1 year validity',
        benefits: ['1 year validity', 'Max Lives: 50', 'Buy License'],
      },
      {
        id: 'gamer-explorer',
        name: 'Explorer',
        price: '$9.99',
        period: '1 year validity',
        benefits: ['1 year validity', 'Max Lives: 100', 'Buy License'],
      },
      {
        id: 'gamer-voyager',
        name: 'Voyager',
        price: '$12.99',
        period: '1 year validity',
        benefits: ['1 year validity', 'Max Lives: 200', 'Buy License'],
      },
      {
        id: 'gamer-wanderer-1000',
        name: 'Wanderer',
        price: '$19.99',
        period: '1 year validity',
        benefits: ['1 year validity', 'Max Lives: 1000', 'Buy License'],
      },
    ],
    visitPath: '/reallives/gamer',
    registerPath: '/reallives/register/gamer',
    registerUrl: 'https://reallivesworld.com/register-gamer',
  },
};
