function buildFirstTechnicalBlog(siteKey) {
  return {
    id: `${siteKey}-why-version-control-systems-are-essential`,
    title: 'Why Version Control Systems Are Essential',
    subtitle:
      'How Linus Torvalds instilled the habit of pulling and pushing code in every programmer',
    excerpt:
      'A beginner-friendly story of why Git exists, how it solved real collaboration pain, and why version control is foundational for every developer.',
    category: 'Version Control',
    tags: ['Software Development', 'Computer Science', 'Beginners'],
    author: 'Viraj Kabbur',
    authorRole: 'Product & Partnerships Lead at RealLives Foundation',
    authorAvatar:
      'https://d2jn82ki4w4ftn.cloudfront.net/reallives-website/common-newsletter-page/viraj-kabbur.jpg',
    publishedOn: 'January 26, 2026',
    readTime: '14 min read',
    readMinutes: 14,
    imagePath:
      'https://d2jn82ki4w4ftn.cloudfront.net/reallives-website/common-newsletter-page/tech-blog-1-bg.webp',
    content: [
      'Before We Begin...',
      "In this article, we'll walk through:",
      'A real-life style story of code sharing gone wrong',
      'Why developers struggled before Git existed',
      'How Linus Torvalds solved this problem',
      'What Git really is (in simple words)',
      'How Git and GitHub are different',
      'Why every developer must learn version control',
      "Let's start from the beginning...",
      `Before diving into "How the web works? the technologies behind it" and "Is AI going to take over all the Web Developers jobs?", let's dive into the basics - how the ecosystem of coding works.`,
      `Yes just like any other ecosystem you might be familiar of, like apple's or samsung's, the world of programming is also driven by ecosystems. If you are a front end developer then your ecosystem might consist of React/Angular/Vue which is very different to a back end developer's ecosystem made up of NodeJS/Express/Nextjs/MongoDB. But the ecosystem both the developer's share is that of Git. Before diving into what Git is, let's explore why and how it came into existence?`,
      'The Classic Pendrive Problem',
      `Let's assume 20 years back Tony was trying to develop a timer app, he was flying through HTML and CSS setting up the look and feel, but as soon as JavaScript made way and logic was needed, he got a bit flustered, maybe because logic did not come to him naturally as he was just starting out. And because AI did not exist back then, he could not just vibe code it. Hence, Tony asked his friend Steve to help him out, legends say Steve was so profound in JS, he used to talk in JS too, English came second.`,
      `Now, Steve was ready to help Tony but he couldn't manage visiting Tony's house as he used to live far away. Hence, Steve asked Tony to send him the code via a pen drive through a post. Tony did as asked and sent Steve the code via the pen drive. Upon receiving the code Steve immediately made changes and even added a few extra features like lapping (lap count and time taken for a lap) and sent the pen drive back to Tony the next day.`,
      `Tony was excited upon receiving the pen drive back, thinking all his problems were fixed. He was glad to see all his problems go away but soon Tony realized that he did not want the lapping feature. He tried to get rid of it but then his program started acting weird, now the only option was to send the code back to Steve. However, this back and forth was not only inconvenient in terms of money but a major waste of time.`,
      'Problems that arise due to lack of Version Control System',
      'Considering Developer A (Tony) and Developer B (Steve) are ready to exchange pen drives back and forth but even then we see in the above diagram, the conflicts that come up when two people work on a code file simultaneously without a VCS. Initially both start editing the code file and create their own versions of the code. The problem arises when they both want to merge their respective versions of code, changes can be easily overwritten or new errors could be introduced.',
      'Problem Summary -',
      'Overwriting Code',
      'Losing Changes',
      'No Collaboration History',
      'Just imagine the back and forth they would have to do just to solve the bugs, let alone add new features',
      `Tony went to sleep that night dreaming of having a system that could solve all his problems, something that would let him collaborate with Steve easily and also maintain their separate code if in case Steve decided to add unnecessary features. What if there was a system that could solve all of this?`,
      'Tech Trivia',
      "The world's first pen drive launched by IBM in the year 2000, with a capacity of 8MB (The size of one picture we take on modern smartphones)",
      "Linus Torvalds - The man who made Tony's dream come true",
      {
        type: 'image',
        src: 'https://d2jn82ki4w4ftn.cloudfront.net/reallives-website/common-newsletter-page/tech-blog-1-img-2.webp',
        alt: 'Linus Torvalds portrait',
      },
      'After Years of Abusive E-mails, the Creator of Linux Steps Aside | The New Yorker',
      `The same night Tony went to sleep peacefully, Linus Torvalds the man who was developing Linux OS at that time, just couldn't sleep. He was done dealing with the large code base of Linux OS. He couldn't manage it anymore, the problem was that Linus himself didn't know what was going on in his own code base, neither was he able to distinguish his stable version nor was he able to understand which feature or function had what effect on his program. He was completely flustered.`,
      'Linus being the smart developer he is, thought of coming up with a system that would help him to manage the large code base. The objective at the beginning was very simple -',
      'Maintain versions of the code',
      'Understand the impact of new functions/features on the existing code',
      'And thus Linus began development of a little side project to help him develop the Linux OS, who knew that this little side project would go on to become Git.',
      "Initially, Linus was successful in creating a system that would track his code, here tracking means telling the difference between the previous (stable version) and the current new version. This alone helped Linus understand the impact of new features or functions on his code. If they were working all right he would just add them to the stable version, if not he would discard them. He now knew exactly which line was causing trouble, nothing would make him happier.",
      'Slowly and steadily Linus kept adding features to his side project which we now know as Git. From tracking the code to being able to maintain a history of the code base and jumping to a point in history that was stable. He did it all, and thus we got Git. Of course his journey was not as simple, I mean dealing with Kernels and OS is not everyones cup of tea, but for the sake of this blog we will keep it short and simple.',
      'If you read this article till here, the following would make sense',
      'Git is a distributed version control software system that is capable of managing versions of source code or data. It is often used to control source code by programmers who are developing software collaboratively.',
      'This is the official definition of GIT on Wikipedia and now I hope it is starting to make sense. I mean instead of manually maintaining 20 versions of my code, I now have a software that runs locally inside my machine right where I code, that on a few commands is not only able to maintain versions of my code but also offers me ways of revisiting any of them at any time. Sounds Great right! It is. We will look into Git commands in another article for which I will add the link right here.',
      'Understanding GIT -',
      'It is open source meaning it is free to use for anybody',
      'It makes tracking of the code much easy',
      'Used for maintaining versions of code like v1,v2.....v124, hence known as Version Control System',
      "It's primary objective is tracking not collaboration",
      'Git and Git Hub are different',
      "These 5 points are more than enough to help understand Git and it's purpose. Linus was kind enough to open source his side project. Git has it's own memory within your code space to maintain your code, I mean of course, without memory how would it be able to store all this data, just that this memory is abstracted from the user. Because of memory it's able to track new changes being made to the code. Git essentially takes a snapshot of your code whenever you want to and then stores it. Initially it has to take the snapshot of your entire code base, but later on it only does so of the changes you make to the code base.",
      'Example -',
      "Let's say your code looked like this in V1. Git takes a snapshot of all 3 lines and stores it in it's memory.",
      {
        type: 'code',
        language: 'text',
        code: ['Hi!', 'This is Viraj', 'I like to Figure out The Web'].join('\n'),
      },
      'Now, assume you made some changes in line 3',
      {
        type: 'code',
        language: 'text',
        code: ['Hi!', 'This is Viraj', 'I like to Figure out The Web and write technical blogs'].join('\n'),
      },
      'Now, instead of taking a snapshot of the entire code, Git understands that line 1 and 2 are unchanged, hence it only saves line 3. This allows Git to stay lightweight even when dealing with large code bases. However, accessing this memory and understanding it is quite interesting, we will see that in another article.',
      "Now back to the fundamentals, point 4. Git was developed keeping a single programmer in mind. It's entire design philosophy is to make the life of a programmer much easy who is working on his own. Hence, it is not in any way similar to Git Hub.",
      'Git Hub is a cloud hosting service that integrates with Git (which is locally running on your computer) to upload your code base on a server so that multiple people can access it and collaborate easily',
      "Git hub's design philosophy is to help people to collaborate on a project using features like cloning, forking, merging and much more. So even if your local machine just catches fire one day, don't worry because Git Hub also acts like a central server for keeping your code safe.",
      "Just between you and me, Git and Git Hub are different, and on a side note, Git is a skill, Git Hub is not, so let's just stop adding it to our resumes. It's like saying I know photo editing and also know how to use Google Photos. I mean Photo editing is a skill, using gphotos to backup your pictures or share it is just an add on.",
      'Why Version Control became mandatory in modern development?',
      'If we imagine the sheer number of people working in these big software companies, we understand that Collaboration is the most important factor that ensures smooth working flow. If there are 100 people working on a single project, can we even imagine their workflow without a VCS. Just imagine there will be 100 versions of the code, then there will be merging all those code files, then solving the conflict issues that come after merging those files and after doing all of this there is no guarantee if that single merged code file would run error free or not break during testing.',
      'Instead of spending time on understanding client/user requirements and solving bugs on production if these developers spent their time on solving issues like conflicts when merging code, maintaining thousands of versions of code, that would be diabolical.',
      'From all of this we can conclude that the most basic ecosystem of coding or programming which is Version Control Systems is as important as any other ecosystem. It is the fundamental driver and the link between the chains of all the software that is being written today.',
      'Git is not a tool you learn later, it is the foundation you build everything on',
      'With that we come to the end of this article. I hope I was able to write a great story on how a Version Control System like Git came into existence in a short and simple way. I do not want to write this cliche line but here we go stay tuned for upcoming blogs on Figuring Out The Web.',
      '#software-development',
      '#computer-science',
      '#beginners',
    ],
    galleryImages: [
      'https://d2jn82ki4w4ftn.cloudfront.net/reallives-website/common-newsletter-page/tech-blog-1-img-1.png',
    ],
  };
}

function buildSecondTechnicalBlog(siteKey) {
  return {
    id: `${siteKey}-git-for-beginners`,
    title: 'Git for Beginners',
    subtitle:
      'Git Fundamentals to git you started. This article will help you understand the basics of Git and how you can get started immediately.',
    excerpt:
      'Understand Git fundamentals—repo, commit, branch, and HEAD—plus a practical walkthrough of your first project and the commands you’ll use daily.',
    category: 'Git Fundamentals',
    tags: ['Git', 'Version Control', 'Beginners'],
    author: 'Viraj Kabbur',
    authorRole: 'Product & Partnerships Lead at RealLives Foundation',
    authorAvatar:
      'https://d2jn82ki4w4ftn.cloudfront.net/reallives-website/common-newsletter-page/viraj-kabbur.jpg',
    publishedOn: 'February 10, 2026',
    readTime: '20 min read',
    readMinutes: 20,
    imagePath:
      'https://d2jn82ki4w4ftn.cloudfront.net/reallives-website/common-newsletter-page/tech-blog-2-bg.webp',
    content: [
      'Before We Begin…',
      'In this article, we’ll walk through:',
      'What Git really is (in simple words)',
      'Why every developer uses Git',
      'Core Git concepts like repo, commit, branch, and HEAD',
      'How GitHub works with Git',
      'Most common Git commands you’ll use daily',
      'A step-by-step walkthrough of your first Git project',
      'The basic Git workflow followed in real projects',
      'By the end of this article, you’ll be confident enough to manage your own projects using Git.',
      'Let’s get started.',
      'What is Git?',
      `The most obvious question, and truthfully it has a very obvious answer. Git is a Distributed Version Control System that allows a programmer to keep track of their code.`,
      `If you want to know why a programmer would want to track their code then you should give a quick read to my first article that explains the need of Git or a VCS.`,
      {
        type: 'link',
        href: `/reallives/${siteKey}/technical-blogs/${siteKey}-why-version-control-systems-are-essential`,
        label: 'Read Part 1: Why Version Control Systems Are Essential',
      },
      `Version Control is essentially a fancy word for backup. The way Whatsapp offers to backup our chats every day/week/month the same way we can backup our code base using Git.`,
      `If you notice we are not talking about Collaboration here, because Git by itself doesn’t have any support for collaboration, but tools like Git Hub, Git Lab, Bit Bucket integrate with Git and offer feature integrations to collaborate with fellow developers.`,
      'Why Git is used?',
      `Git is used to keep track of our code base. Well what does tracking help in? What does it solve for us?`,
      `Tracking helps us keep our code base organized. It’s not a written rule that without Git, programming cannot be done, it can be—but if you want to become a better, faster and more efficient programmer, Git is the way to go.`,
      `Git also helps a developer to maintain different versions of the code at the same time.`,
      `Let’s say, you add a new feature to your code base and it causes your app to crash. Without Git it would have been difficult for you to revert back to the error free app version, but Git pinpoints the exact version with the exact code that was previously stable.`,
      `Maybe you want to add 2-3 different approaches to a problem you might be facing in the code base. With Git you can just create branches and apply your solutions in each one without hampering the original code base.`,
      `Branching is essentially creating duplicates of your main code file.`,
      `Now, let’s get a bit hands on with Git.`,
      'Git Basics and Core Terminologies',
      'Repository (Repo) -',
      `When you want to start using Git to track your code you enter the git init command inside the terminal of your project folder. This tells Git to start tracking your project folder and creates a hidden .git folder (the repository).`,
      { type: 'code', language: 'bash', code: 'git init' },
      'Staging Area -',
      `Once Git is initialized and you’ve written some code, it’s time to tell Git to keep track of it.`,
      {
        type: 'code',
        language: 'bash',
        code: ['git add .', '# or track a single file', 'git add index.html'].join('\n'),
      },
      `This is a temporary area where you select which files will be tracked and which won’t in the next commit.`,
      'Commit -',
      `Now that you have told Git which files to track, it’s time to actually save those files (take a snapshot).`,
      { type: 'code', language: 'bash', code: 'git commit -m "my first commit"' },
      `The -m signifies that you can pass a message along with your commit.`,
      'Branch -',
      `Branches are like streams that allow you to perform different development tasks simultaneously. By default Git serves you with a main branch. You can create multiple branches and experiment safely.`,
      { type: 'code', language: 'bash', code: ['git checkout -b feature-idea', '# later...', 'git checkout main'].join('\n') },
      'HEAD -',
      `HEAD means your current position in the code base (current commit/branch).`,
      { type: 'code', language: 'bash', code: ['git status', 'git log --oneline --decorate --graph'].join('\n') },
      `Till here we saw the basics of Git but in modern software development you will not just be using Git but also a collaboration tool to communicate with your peers. Hence, let’s understand some basic concepts of GitHub.`,
      'Git Hub Basics',
      'Clone -',
      `To download a public repository onto your local machine:`,
      { type: 'code', language: 'bash', code: "git clone 'https://github.com/username/repo.git'" },
      'Push -',
      { type: 'code', language: 'bash', code: 'git push origin main' },
      'Pull -',
      { type: 'code', language: 'bash', code: 'git pull origin main' },
      'Merge -',
      { type: 'code', language: 'bash', code: 'git merge branch-2' },
      `Note - many a times this leads to merge conflicts. Git alerts you when code overlaps and highlights the culprit sections.`,
      'Common Git Commands',
      {
        type: 'code',
        language: 'bash',
        code: [
          'git init',
          'git add .',
          'git commit -m "message"',
          'git status',
          'git log',
          'git clone <url>',
          'git push origin main',
          'git pull origin main',
          'git checkout <branch-name>',
          'git checkout -b <branch-name>',
          'git reset --hard <commit-hash>',
          'git merge <branch-name>',
          'git rebase <branch-name>',
          'git merge --squash <branch-name>',
          'git cherry-pick <commit-hash>',
        ].join('\n'),
      },
      'Mini Walkthrough: Your First Git Project (Step-by-Step)',
      'Step 1: Create a Project Folder',
      `Example:`,
      { type: 'code', language: 'text', code: 'MyWebsite/' },
      `Inside this folder, create a file called:`,
      { type: 'code', language: 'text', code: 'index.html' },
      `Add some basic code:`,
      {
        type: 'code',
        language: 'html',
        code: ['<html>', '  <body>', '    <h1>Hello Git!</h1>', '  </body>', '</html>'].join('\n'),
      },
      'Step 2: Initialize Git',
      { type: 'code', language: 'bash', code: 'git init' },
      'Step 3: Check Status',
      { type: 'code', language: 'bash', code: 'git status' },
      'Step 4: Add File to Staging Area',
      { type: 'code', language: 'bash', code: ['git add index.html', '# or', 'git add .'].join('\n') },
      'Step 5: Commit Your Changes',
      { type: 'code', language: 'bash', code: 'git commit -m "Added first HTML file"' },
      'Step 6: Connect to GitHub (Remote Repository)',
      {
        type: 'code',
        language: 'bash',
        code: ['git remote add origin <repository-url>', '# example', 'git remote add origin https://github.com/username/my-website.git'].join(
          '\n'
        ),
      },
      'Step 7: Push Code to GitHub',
      { type: 'code', language: 'bash', code: 'git push -u origin main' },
      'Step 8: Making Future Changes',
      { type: 'code', language: 'bash', code: ['git add .', 'git commit -m "Updated homepage design"', 'git push'].join('\n') },
      'Summary: The Git Flow',
      { type: 'code', language: 'text', code: 'Edit → Add → Commit → Push' },
      `With that we come to the end of this article. I hope I was able to explain Git and it’s basic functionalities in a simple way. Stay tuned for upcoming blogs on Figuring Out The Web.`,
    ],
  };
}

function buildThirdTechnicalBlog(siteKey) {
  return {
    id: `${siteKey}-deep-diving-inside-git`,
    title: 'Deep Diving Inside Git',
    subtitle: 'How Git Works and the Role of the .git Folder',
    excerpt:
      'Go behind the scenes of Git: snapshots, hashes, commit/tree/blob objects, HEAD and branch pointers, the .git directory, and how reflog helps recover “lost” commits.',
    category: 'Git Internals',
    tags: ['Git', 'Version Control', 'Internals'],
    author: 'Viraj Kabbur',
    authorRole: 'Product & Partnerships Lead at RealLives Foundation',
    authorAvatar:
      'https://d2jn82ki4w4ftn.cloudfront.net/reallives-website/common-newsletter-page/viraj-kabbur.jpg',
    publishedOn: 'February 27, 2026',
    readTime: '18 min read',
    readMinutes: 18,
    imagePath:
      'https://d2jn82ki4w4ftn.cloudfront.net/reallives-website/common-newsletter-page/tech-blog-3-bg.webp',
    content: [
      'Before We Begin…',
      'In this third part of the Git 101 series, we will dive deep into the working of Git and explore it’s behind the scenes.',
      "In this article, we’ll go behind the scenes and understand how Git actually works.",
      'We’ll explore:',
      'What really happens when you create a commit',
      'How Git stores your code internally',
      'The concept of snapshots and hash values',
      'Git’s three core objects: Commit, Tree, and Blob',
      'How HEAD, branches, and pointers are connected',
      'What’s inside the .git folder',
      'How Git helps you recover lost commits using reflog',
      'By the end of this article, Git will no longer feel like “magic” — you’ll know exactly what’s happening under the hood.',
      'Let’s dive in.',
      'Quickly what is Git?',
      'Git is a Version Control System that is used to track the changes made to our files and folder. A VCS plays a very important role while developing an application of any sort.',
      'How Git actually works?',
      'At it’s very core Git is a content-addressed database which does not care about files but cares only about the snapshots which are represented via unique hash codes.',
      'So, when you commit, Git -',
      'Takes a snapshot of the folder',
      'Breaks it into objects',
      'Stores them into the .git folder',
      'Links them together',
      'Git Snapshots',
      'Think of snapshots like a screenshot that you take in your phone, just like your screenshot has some information of the screen that you captured along with some admin details like time and date, similar is a git snapshot.',
      'A git snapshot is executed when you commit your files which are already in the staging area. The snapshot saves all the information available of your folder at that time in the .git folder. The .git folder is a crucial component of this entire process but remains hidden or abstracted from the user for better User Experience.',
      'You must be thinking, well, why do we need to store all this information? The answer is pretty straightforward, it is to enable git to tell us the difference between our different code versions.',
      'Example -',
      { type: 'code', language: 'text', code: ['hi!', '', '(commit #1)'].join('\n') },
      'Now, I staged and committed this and a commit number 1 was created.',
      'After some time I again made some changes to the file',
      { type: 'code', language: 'text', code: ['hi!', 'This is viraj.', '', '(commit #2)'].join('\n') },
      'I added line number 2. Now when I stage and commit my file and create commit number 2, Git will see the difference (known as diff in git) and exactly tell me that line 2 was added in commit number 2',
      { type: 'code', language: 'diff', code: ['hi!', '++ This is viraj.'].join('\n') },
      'A git snapshot is identified by a unique hash code and this code is also known as a commit id.',
      {
        type: 'code',
        language: 'text',
        code: '884d5631253f7faaa6edee5e5cb3f68bd21bb2e7',
      },
      'Every snapshot/commit has it’s own unique hash code.',
      'Hope you now know why we need to store information of our project folder from time to time, and how we use staging and committing to take snapshots of our project and store it in the .git folder.',
      'Now, let’s look at the 3 building blocks of Git’s internals.',
      'Git Building Blocks',
      'Git stores everything as 3 main objects',
      'Commit Object',
      'Tree Object',
      'Blob Object',
      'Let’s understand one by one',
      'Commit Object',
      'Commit consists of snapshot + info',
      {
        type: 'code',
        language: 'text',
        code: ['tree <tree-hash>', 'parent <parent-hash>', 'author Viraj', 'committer Viraj', 'commit message'].join(
          '\n'
        ),
      },
      { type: 'code', language: 'text', code: 'A --> B --> C' },
      'C will have the hash of B and B will have the hash of A as reference. This is to form history.',
      'Tree Object',
      'It stores files, folders, nests and their hashes along with blobs. Tree object is present inside the commit object.',
      { type: 'code', language: 'text', code: ['File Mode', 'File Name', 'File Hash', 'Parent Tree Object'].join('\n') },
      'Example -',
      { type: 'code', language: 'text', code: ['src/', ' ├─ app.js', ' └─ utils.js'].join('\n') },
      'Blob Object',
      'Contains only the metadata, no file path, no file name. Blob Object is present in the tree object and contains the actual file content. This is the place where the file content is stored.',
      'This is how the structure of the Git Building Block’s looks like.',
      'How Everything Connects?',
      { type: 'code', language: 'text', code: 'HEAD --> Branch --> Commit Object --> Tree Object --> Blob Object' },
      'This is the internal workflow of Git.',
      'What Happens When You Commit?',
      'When you do:',
      { type: 'code', language: 'bash', code: 'git commit -m "msg"' },
      'Git:',
      'Step 1',
      'Reads staged files from index',
      {
        type: 'code',
        language: 'text',
        code: ['project/', ' ├── index.html', ' └── src/', '     └── app.js'].join('\n'),
      },
      'Step 2',
      'Creates blobs for new content',
      { type: 'code', language: 'text', code: ['index.html → blob hash'].join('\n') },
      'Step 3',
      'Creates trees for folders',
      {
        type: 'code',
        language: 'text',
        code: ['Tree (root)', ' ├── index.html → blob', ' └── src → tree', '        └── app.js → blob'].join('\n'),
      },
      {
        type: 'code',
        language: 'text',
        code: ['tree <root-tree-hash>', 'parent <previous-commit-hash>', 'author ...', 'message ...'].join('\n'),
      },
      'Step 4',
      'Creates commit pointing to root tree',
      'Step 5',
      'Moves branch pointer',
      'Helpful commands',
      'Here are some helpful commands that you can use to explore the git internals:',
      { type: 'code', language: 'bash', code: 'git cat-file -p HEAD' },
      'Grab tree id from the above command and use it in the following command to get the tree object:',
      { type: 'code', language: 'bash', code: 'git ls-tree HEAD' },
      'Grab blob id from the above command and use it in the following command to get the blob object:',
      { type: 'code', language: 'bash', code: 'git cat-file -p <blob-hash>' },
      'Role of .git folder',
      'When you do:',
      { type: 'code', language: 'bash', code: 'git init' },
      'Git creates:',
      { type: 'code', language: 'text', code: '.git/' },
      'This folder contains everything.',
      'If .git is deleted → repo is dead',
      'Important Parts Inside .git',
      {
        type: 'code',
        language: 'text',
        code: [
          '.git/',
          '│',
          '├── objects/     ← All commits, files, folders (compressed)',
          '├── refs/        ← Branches & tags',
          '├── HEAD         ← Current branch pointer',
          '├── index        ← Staging area',
          '├── config       ← Repo config',
          '├── logs/        ← Reflog (history of HEAD)',
        ].join('\n'),
      },
      'Let’s see what they do.',
      '.git/objects/ → Database',
      'This is where Git stores:',
      'Commits',
      'Files',
      'Folders',
      'All as objects.',
      'Example:',
      { type: 'code', language: 'text', code: '.git/objects/ab/12cd34ef...' },
      'First 2 chars = folder',
      'Rest = filename',
      'This is from the hash.',
      '.git/refs/ → Branches & Tags',
      'Example:',
      { type: 'code', language: 'text', code: 'refs/heads/main' },
      'Contains:',
      { type: 'code', language: 'text', code: 'f3a1c9e...' },
      'That is → commit hash',
      'So:',
      'Branch = pointer to commit',
      'Nothing more.',
      '.git/HEAD → Where You Are',
      'Contains:',
      { type: 'code', language: 'text', code: 'ref: refs/heads/main' },
      'Means:',
      'You’re on main',
      'If detached HEAD:',
      { type: 'code', language: 'text', code: 'f3a1c9e...' },
      'Then you’re directly on a commit.',
      '.git/index → Staging Area',
      'This is:',
      'The staging area file',
      'When you do:',
      { type: 'code', language: 'bash', code: 'git add file.txt' },
      'It updates index.',
      'So:',
      { type: 'code', language: 'text', code: 'Working Dir → Index → Commit' },
      '.git/config → Repo-Level Settings (Local Only)',
      'This file stores settings for this specific repository.',
      'Not global. Not system. Only this repo.',
      'What It Contains',
      {
        type: 'code',
        language: 'ini',
        code: [
          '[core]',
          '    filemode = true',
          '    bare = false',
          '',
          '[remote "origin"]',
          '    url = https://github.com/user/repo.git',
          '    fetch = +refs/heads/*:refs/remotes/origin/*',
          '',
          '[branch "main"]',
          '    remote = origin',
          '    merge = refs/heads/main',
        ].join('\n'),
      },
      'Meaning',
      '[core] → Basic Behavior',
      'filemode → Track file permissions',
      'bare → Is this a bare repo?',
      '[remote "origin"] → Remote Info',
      'url → Where to push/pull',
      'fetch → What branches to download',
      'Used when you run:',
      { type: 'code', language: 'bash', code: ['git push', 'git pull'].join('\n') },
      '[branch "main"] → Branch Tracking',
      'Links main → origin/main',
      'That’s why:',
      { type: 'code', language: 'bash', code: 'git pull' },
      'works without extra arguments.',
      '.git/logs/ → Reflog (Pointer History)',
      'Reflog stores history of where HEAD and branches pointed.',
      'Not commit history',
      'Pointer movement history',
      'Structure',
      { type: 'code', language: 'text', code: ['.git/logs/', ' ├── HEAD', ' └── refs/heads/main'].join('\n') },
      'Meaning',
      '.git/logs/HEAD',
      'Tracks every move of HEAD',
      'Format:',
      { type: 'code', language: 'text', code: 'oldhash newhash user date message' },
      'Means: HEAD moved from old → new',
      '.git/logs/refs/heads/main',
      'Tracks movement of main branch',
      'Logs commits, reset, rebase, etc.',
      'Purpose (Why It Exists)',
      'Git assumes you’ll make mistakes',
      'So reflog keeps a local backup of pointer changes.',
      'Recover Deleted Commits',
      'If you run:',
      { type: 'code', language: 'bash', code: 'git reset --hard HEAD~3' },
      'Commits disappear.',
      'Recover using:',
      { type: 'code', language: 'bash', code: ['git reflog', 'git reset --hard <hash>'].join('\n') },
      'Important',
      'Reflog is:',
      'Not pushed',
      'Not shared',
      'Local only',
      'Delete repo = reflog gone.',
      'With this we have come to the end of the Git 101 series, I hope you found it easy to understand and helpful enough to actually implement Git in your daily workflow. I will be coming up with more such series that will help you figure out the web!',
      'Cheers, Viraj',
    ],
  };
}

export const technicalBlogsContent = {
  school: {
    heading: 'Technical Blogs',
    intro:
      'Engineering stories, fundamentals, and practical guides for builders straight from the RealLives team, sharing the systems, insights, and innovations behind immersive life simulation.',
    articles: [
      buildThirdTechnicalBlog('school'),
      buildSecondTechnicalBlog('school'),
      buildFirstTechnicalBlog('school'),
    ],
  },
  university: {
    heading: 'Technical Blogs',
    intro:
      'Engineering stories, fundamentals, and practical guides for builders straight from the RealLives team, sharing the systems, insights, and innovations behind immersive life simulation.',
    articles: [
      buildThirdTechnicalBlog('university'),
      buildSecondTechnicalBlog('university'),
      buildFirstTechnicalBlog('university'),
    ],
  },
  homeschooler: {
    heading: 'Technical Blogs',
    intro:
      'Engineering stories, fundamentals, and practical guides for builders straight from the RealLives team, sharing the systems, insights, and innovations behind immersive life simulation.',
    articles: [
      buildThirdTechnicalBlog('homeschooler'),
      buildSecondTechnicalBlog('homeschooler'),
      buildFirstTechnicalBlog('homeschooler'),
    ],
  },
};

